# Generated by Django 4.0.1 on 2022-02-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteTitle', models.CharField(max_length=50)),
                ('noteBody', models.TextField()),
                ('noteCreatedDate', models.DateTimeField(editable=False)),
                ('noteUpdatedDate', models.DateTimeField()),
                ('enabled', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.user')),
            ],
        ),
    ]
